### ISSUE TITLE
[Feature Request] Port RFLink to support LimeSDR?

### ISSUE THREAD

**Issue by Hedda** [ClearlyClaire/RFLink#1]
Maybe a few days early to to ask this, but do you think that RFLink could be ported to support LimeSDR?

http://limesdr.org

LimeSDR is (or rather will be) a open source low-cost software defined radio through which apps can be programmed to support any type of wireless standard, e.g. WiFi, UMTS, LTE (4G/5G), LoRa, Bluetooth, Zigbee, RFID, DVB Digital Broadcasting, etc.

Additional info here about this Canonical/Ubuntu-backed LimeSDR (LimeSDR.org) project which aim to crowd-source for app-enabled SDR (Software-Defined Radio) open source programmable hardware the third week of april:

http://insights.ubuntu.com/2016/02/26/mobile-world-congress-2016-day-4-recap/
http://insights.ubuntu.com/2016/03/23/mwc-2016-our-biggest-show-yet/
http://insights.ubuntu.com/2016/04/07/when-a-projector-and-app-enabled-software-defined-radio-cross-paths/

According to the LimeSDR.org project will crowd-source their app-enabled SDR (Software-Defined Radio) hardware any day now or either Kickstarter or InfieGoGo:

https://www.crowdsupply.com/lime-micro/limesdr

LimeSDR.org have also re-announced this crown-sourcing effort on Twitter

https://twitter.com/LimeSDR_org

**Comment by ClearlyClaire** [comment]
Hi! Sorry, I'm not the upstream developper of RFLink, nor am I maintaining my fork.
http://www.nemcon.nl/blog2/
