### ISSUE TITLE
Plugin_031.c, WS-1200 Battery Low

### ISSUE THREAD

**Issue by Portisch** [ClearlyClaire/RFLink#2]
The Format
`AAAAAAA AAAABBBB BBBBCCCC CCCCCCCC DDDDDDDD DDDDDDDD EEEEEEEE FFFFFFFF`
for the WS-1200 isn't correct!

`AAAAAAA AAAABBBB BBBBZCCC CCCCCCCC DDDDDDDD DDDDDDDD EEEEEEEE FFFFFFFF`
Temperature is only 11 bits - not 12.
Z: Battery low status, 0 - OK, 1, battery low

**Comment by ClearlyClaire** [comment]
Hi! Sorry, I'm not the upstream developper of RFLink, nor am I maintaining my fork.
http://www.nemcon.nl/blog2/
