### ISSUE TITLE
Delete all records

### ISSUE THREAD

**Issue by jiripaskov** [ClearlyClaire/RFLink#3]
How to delete all records from rflink? 
10;RFFind;0; (0 means number of record)- doesn´t work,
Firmware reflash - doesn´t work.

Seems like some bug. (R48 fw)

Please help.

**Comment by ClearlyClaire** [comment]
Sorry, as the repo states, it's a (stale) unofficial mirror of RFLink. I have no experience with recent versions of RFLink and thus cannot help you. Please redirect your query upstream.
